[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
civicchain = "Hh6rbt3exyZL95JVsJqBBs2cLDZ5jD1LV2Rzh494Nbj6"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
