[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
civicchain = "12D76ecL7prNejn2PgyAebvrF5FrKpnY7ABNW5Zm2Qrm"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
